name: ci

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno fmt --check .
      - run: deno lint .
      - run: deno check ./pkgm.ts

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/setup@v3
      - run: ./pkgm.ts i git
      - run: /usr/local/bin/git --version

      - run: ./pkgm.ts i pkgx.sh/brewkit
      - run: /usr/local/bin/bk --help

      - run: ./pkgm.ts i xpra.org # https://github.com/pkgxdev/pkgm/issues/13
      - run: xpra --version
